### ISSUE TITLE
server redirect for http://2016.fldrupal.camp/

### ISSUE THREAD

**Issue by ThatGuyCND** [mherchel/fldc-issues#10]
should resolve and redirect to http://fldrupal.camp

**Comment by JCL324** [comment]
Added new sub-domain for 2016. Waiting for propagation.

**Comment by JCL324** [comment]
This is now working as requested, but it really should participate in the fldrupal.camp redirect to https://www.fldrupal.camp.  Not critical but leaving open for now.

**Comment by JCL324** [comment]
Finally fixed.
