### ISSUE TITLE
Session acceptance

### ISSUE THREAD

**Issue by ultimike** [mherchel/fldc-issues#148]

**Comment by ultimike** [comment]
@AmyJuneH If you have some time, would you be so kind as to go through the proposed sessions and let us know if we have a good mix of proposals? We want to make sure we have a few for each of our proposed tracks.

If not, we'll need to start soliciting specific topics.

thanks,  
-mike

**Comment by AmyJuneH** [comment]
@ultimike 

Beginner Track - 3

Being human - 6

Design, theming, front-end - 2

Development & Performance - 2

Non-session

Project Management and consulting - 2

Off the island - 2

SIte building - 4

**Comment by AmyJuneH** [comment]
Sessions scheduled. Closing issue.
