### ISSUE TITLE
Friday full- and half-day trainings

### ISSUE THREAD

**Issue by ultimike** [mherchel/fldc-issues#149]
I'm willing to do one (module development). 

Adam Bergstein and Ryan Bateman are interested in doing a Drupal + Gatsby training.

Possibly AmyJune on some contribution stuff.

Joe and Amber from Lullabot - theming

Steve Burge from OSTraining - intro to Drupal

React - John Tucker

**Comment by mherchel** [comment]
@AmyJuneH are you handling trainings? We need to start reaching out to everyone and get content on the site.

**Comment by jordanafung** [comment]
Hey @mherchel I was going to do this.
Will send these out today!
Where can I find the email addresses for everybody?

**Comment by mherchel** [comment]
Awesome! Just sent you an invite so we can assign it to you. Can you set up a google spreadsheet and share it with me, and i'll update it?

**Comment by jordanafung** [comment]
Great thanks!
I haven't gotten an invite as yet (not sure what I am looking for?)
Here is the Google Sheet:
https://docs.google.com/spreadsheets/d/1Q31HiPZ5Ta7Cqbay6gSJaKWGYBtsKGUgoQ1Qz7HwEFY/edit?usp=sharing

**Comment by mherchel** [comment]
Just invited you to this github org. It looks like @ultimike did it before, so you might have to dig through your email

![image](https://user-images.githubusercontent.com/1605905/49590531-24770780-f93a-11e8-9f05-89ca656402a3.png)

I'll input stuff in the spreadsheet

**Comment by jordanafung** [comment]
Thanks Mike!

**Comment by jordanafung** [comment]
Hey guys - just wondering if there is an email address I need to cc for the Florida camp stuff?
Here is the template for the email I want to send out:

Hi {{ NAME }}
My name is Jordana Fung and am contacting you on behalf of the organizers of Florida Drupalcamp 2019 <<https://fldrupal.camp>> .
We've understood that you may be interested in presenting a training about {{ TOPIC }} at our Florida camp on Friday February 15th in Orlando and we would love to have you.
We would love to verify a few things with you:
1. Are you available to give the training on Friday February 15th at 9 am (or 1 pm for Half day training)?
2. There are options to do:
 - Half day training (approx. 9 am to 12 pm or 1 pm to 4 pm) and 
- Full day training (approx. 9 am - 4 pm with lunch break).
Which would you prefer? (Note that you may modify the times to suit your training.)
3. Please provide the title, description and presenters of your training and any prerequisites needed

If you have any questions, please don't hesitate to ask. 

If you are thinking of also doing a talk, you can submit your session here <<https://www.fldrupal.camp/submit-session>> and don't forget to spread the love <<https://twitter.com/fldrupalcamp >>

Thank you and we look forward to seeing you soon!

Jordana Fung (on behalf of Florida Drupalcamp 2019)

**Comment by ultimike** [comment]
@jordanafung You can cc info@fldrupalcamp.org

**Comment by mherchel** [comment]
Also note that they do not need to submit a session. The session nodes are different than the training nodes (which you'll create)

**Comment by jordanafung** [comment]
Cool - I'll change the text about session submission to make it clearer that they can also submit a session.
Can you guys help me fill out some details on the length for the Full vs half day training? and what time we want to start?

Thanks!

**Comment by mherchel** [comment]
Starts at 9am. Break (with food - usually publix subs or something) at noonish, then continue till 3ish. 

The instructor can obviously go shorter or longer if they desire.

**Comment by mherchel** [comment]
We'll have folks in the building at 8:30 to start taking registrations, and point people where to go

**Comment by jordanafung** [comment]
Ok, just to verify -  so full day is 9 - 3 with a lunchbreak around noon. and half day is 9 - 12?

**Comment by mherchel** [comment]
Yes. But instructors can modify that as they see fit.

**Comment by ultimike** [comment]
Full day is 9-4. We can also do half-days from 1-4 if instructors prefer.

**Comment by jordanafung** [comment]
Oops - luckily I just sent you the first email to test out :)
Updated the times in template above

**Comment by jordanafung** [comment]
@ultimike can you check to see if you approve of the 2nd email (times edited) and I'll send out the rest.
Thanks guys!

**Comment by jordanafung** [comment]
Emails sent - will update spreadsheet accordingly

**Comment by ultimike** [comment]
I just heard from Steve Burge - he won't be able to attend FLDC19. 

So, we'll either need to find someone else to teach his intro course or take it off the schedule.

-mike

**Comment by capysara** [comment]
Ah, the drop down when you register doesn't match the trainings page. https://www.fldrupal.camp/trainings. I can update if I have the current info and access.

**Comment by ultimike** [comment]
I'll need someone to confirm that what is listed on
https://www.fldrupal.camp/trainings is correct (please check dates - also
it says the React training is sold out?). Once that is done, I'll make sure
EventBrite matches it.

thanks,
-mike

**Comment by capysara** [comment]
According to the spreadsheet:
Michael Anello - Module Development
Amy June - Contribution Stuff
Joe & Amber Drupalize.me - Theming
Intro to Drupal (maybe if we find someone to teach)?
John Tucker - React
Adam Bergstein and Ryan Bateman - Drupal / Gatsby

**Comment by ultimike** [comment]
@jordanafung Looks like the https://www.fldrupal.camp/trainings page needs to be updated - let myself or @mherchel know if you need access or additional information.

thanks,  
-mike

**Comment by jordanafung** [comment]
Trainings page has been updated and trainers have been notified.
Thanks!

**Comment by AmyJuneH** [comment]
Camp has concluded. Closing issue. D.o attributions given.
