### ISSUE TITLE
Saturday catering

### ISSUE THREAD

**Issue by ultimike** [mherchel/fldc-issues#158]

**Comment by andrewmriley** [comment]
Email sent. Waiting on info back.

**Comment by andrewmriley** [comment]
Email was received. Phil is working on an estimate for 250 users. Number isn't final. Just used for budgeting purposes.

**Comment by andrewmriley** [comment]
Estimate for 250 users: $5916.75

**Comment by andrewmriley** [comment]
Tagging #142 for this issue as well since I'll need an updated logo

**Comment by ultimike** [comment]
Registration numbers are lower than last year - might want to get an
estimate for 180 if you think Gringos needs a better number at this time.

-mike

**Comment by andrewmriley** [comment]
Forgot to update this ticket. I let Gringos Locos know we're going for 190.

**Comment by andrewmriley** [comment]
Invoice passed on for payment via email.
