### ISSUE TITLE
CAPTCHA is broken on /user/register

### ISSUE THREAD

**Issue by mherchel** [mherchel/fldc-issues#16]
![image](https://cloud.githubusercontent.com/assets/1605905/12218590/9fd68fba-b6f1-11e5-8bd8-7ea6a1f8aea5.png)

**Comment by mherchel** [comment]
going to disable for now

**Comment by iribarne** [comment]
It looks like the database updates done by John may have fixed this as well. I enabled re-captcha on the user_register_form, and the re-captcha looks good (see screenshots below).
![user_register_form](https://cloud.githubusercontent.com/assets/617832/12333229/023e6e16-bac1-11e5-81a5-a9e2b5faeaf6.png)
![create_new_account](https://cloud.githubusercontent.com/assets/617832/12333233/07f1eb80-bac1-11e5-8c87-1b340fd87efc.png)

screenshot),

**Comment by ultimike** [comment]
Are the recaptcha keys being used even for this domain? Or are they for the fldrupal.camp domain?

How about we just disable recaptcha for now and use a plain-old math captcha until after launch?

-mike

**Comment by mherchel** [comment]
Changed to Math. Closnig
