### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by ultimike** [mherchel/fldc-issues#161]
WebEnabled/DevPanel will be providing branded lanyards as well as will have their logo featured on the front of the name badges (as part of their sponsorship).

**Comment by mark-casias** [comment]
@ultimike do we have a design for the badges or what needs to be done for this? Just order them?

**Comment by ultimike** [comment]
@mark-casias Normally, the person in charge of badges does it all - creates/secures the design, gets the attendee list in .csv format (I can provide that), does the merge (so that names are pre-printed on the badges), arranges for printing, and delivers them to Caroline on Friday of the camp.

Obviously, everything from the .csv on needs to be done in the week leading up to the event. Just provide me with an estimate of costs and we'll get you reimbursed.

We're getting lanyards from a sponsor this year, so we just need to make sure we have plenty of blank badges for late signups, walkins, etc...

I believe @Ky1e took care of the badges last year - he can chime in if I'm missing anything.

-mike

**Comment by mark-casias** [comment]
Sounds good.. I'll take this one then. I'll wait til https://github.com/florida-drupalcamp/fldc-issues/issues/142 is updated and then have everything set up by the end of the month. I can't assign this to myself so this is me claiming it.

**Comment by carolineachee** [comment]
Mike,

I read somewhere that the lanyards are being supplied.... We need to know what type clip will be on them to insure that we can clip the badges.

Thanks,
Caroline

**Comment by ultimike** [comment]
Good point - I'll ask Salim and report back.

thanks,
-mike

**Comment by ultimike** [comment]
I've already communicated with Caroline via email about this - but we'll be taking care of the lanyards ourselves.

**Comment by carolineachee** [comment]
Good Morning!!

Attached is a excel file with the Badge Information.  We will also need 50 blank name tags for all those who registered late...
[NameTagInformation.xlsx](https://github.com/florida-drupalcamp/fldc-issues/files/2851340/NameTagInformation.xlsx)

Thank you,
Caroline

**Comment by mark-casias** [comment]
Badges have been ordered and should arrive at @ultimike's house on Thursday.

**Comment by carolineachee** [comment]
Thank-you!! 

Will we need to punch slots in the badge?

Thanks!
Caroline

**Comment by mark-casias** [comment]
negative. I ordered the ones that had a slot on the top

**Comment by carolineachee** [comment]
Mark!!

Thank you very very much!
Caroline and Karan

**Comment by Ky1e** [comment]
Badges ordered. Closing this out.
