### ISSUE TITLE
Session scheduling

### ISSUE THREAD

**Issue by ultimike** [mherchel/fldc-issues#164]
Sunday sessions should start at 10am and end by 3pm.

**Comment by carolineachee** [comment]
Is anyone making a printed copy of the session schedule???

**Comment by carolineachee** [comment]
Also the web indicates that Sunday the opening is at 9:00 and sessions start at 9:30....

**Comment by AmyJuneH** [comment]
@carolineachee what is your d.o profile name?

**Comment by AmyJuneH** [comment]
Camp concluded. D.O attributions given. Closing issues.

**Comment by carolineachee** [comment]
AmyJune,

 

My drupal name is cachee

 

Caroline
