### ISSUE TITLE
Sunday sprints

### ISSUE THREAD

**Issue by ultimike** [mherchel/fldc-issues#166]
Need to make sure this page is up-to-date: https://www.fldrupal.camp/contribution-sprints

**Comment by AmyJuneH** [comment]
I can create and change this copy this weekend.

**Comment by ultimike** [comment]
Thank you, @AmyJuneH!

-mike

**Comment by AmyJuneH** [comment]
Badcamp had some folks from the community display some discord over the word "Sprint" - Could the menu link be changed ??
@ultimike

**Comment by ultimike** [comment]
Change to "Community day"? Something else?

**Comment by AmyJuneH** [comment]
I changed the menu title, looks good on wide screen and mobile.

Changed copy to reflect having mini sprint workshops. Changed the word "sprint" when appropriate.

**Comment by AmyJuneH** [comment]
Set up worksheets and issues
