### ISSUE TITLE
Error on account creation

### ISSUE THREAD

**Issue by mherchel** [mherchel/fldc-issues#17]
Error when creating a regular account
````
Notice: Undefined variable: mailkey in logintoboggan_user_register_submit() (line 525 of /mnt/www/html/fldrupalcampstg/docroot/sites/all/modules/contrib/logintoboggan/logintoboggan.module).
Notice: Undefined variable: text in _user_mail_text() (line 2870 of /mnt/www/html/fldrupalcampstg/docroot/modules/user/user.module).
Notice: Undefined variable: text in _user_mail_text() (line 2870 of /mnt/www/html/fldrupalcampstg/docroot/modules/user/user.module).

````
![image](https://cloud.githubusercontent.com/assets/1605905/12218607/32998eb0-b6f2-11e5-9fe6-9dd44e23f45d.png)

**Comment by mherchel** [comment]
@JCL324 You want to take a look at this?

**Comment by iribarne** [comment]
This is a permissions issue. Currently, only administrators can create accounts (see screenshot):

![original_accounts_permissions](https://cloud.githubusercontent.com/assets/617832/12337511/7f79ace4-bad8-11e5-8459-5b8212b3321c.png)

Changed accounts permission to "Visitors, but with administrator approval is required."

![new_accounts_permission](https://cloud.githubusercontent.com/assets/617832/12337545/b1af674e-bad8-11e5-933b-f8d33026e250.png)

Able to create accounts as a visitor (admin approval is required for now, but this may have to change later when the site goes live).

![message_after_account permission_change](https://cloud.githubusercontent.com/assets/617832/12337581/dc1d1850-bad8-11e5-92be-8bf063cf5b66.png)

**Comment by ultimike** [comment]
Hector,

So, with the permission fix can this issue be closed?

-mike

**Comment by iribarne** [comment]
Mike,

Yes, as long as it is not "Administrators only."  I set it to visitors with admin permission and no email verification for staging, but when the site launches that may have to be changed.

-Hector
