### ISSUE TITLE
Update fldrupalcamp.org SPF DNS record

### ISSUE THREAD

**Issue by mherchel** [mherchel/fldc-issues#171]
@JCL324 Can you update the SPF txt record for the `fldrupalcamp.org` domain? 

Transactional emails are ending up in spam bins, and this should resolve this. 

The updated value is:
`"v=spf1 include:_spf.google.com include:spf.pantheon.io include:servers.mcsv.net ~all"`

**Comment by JCL324** [comment]
Done. Here are the updated records: 
<img width="994" alt="image" src="https://user-images.githubusercontent.com/2161188/49396251-87c02a00-f6ed-11e8-990b-90ad1c0d4532.png">

The TTL was "default", not sure what it that value is. Changed to 5 min. but might take a bit to propagate.

**Comment by JCL324** [comment]
Verified on SPF lookup here: https://mxtoolbox.com/SuperTool.aspx?action=mx%3afldrupalcamp.org&run=toolpage#.
