### ISSUE TITLE
In-kind sponsorships

### ISSUE THREAD

**Issue by ultimike** [mherchel/fldc-issues#172]
Drupalize.me - two 6-months memberships for us to give away.

**Comment by mherchel** [comment]
We should print out a certificate, so we have something to hand out. They typically just give us coupon codes. Can we create a task for this ?

**Comment by ultimike** [comment]
I don't think we need a separate task - just someone willing to take charge of this task.

**Comment by mherchel** [comment]
FYI, JetBrains is giving us 3 licenses to give away. Plus a bunch of stickers. #173

**Comment by AmyJuneH** [comment]
OK - let me know what I have to do, I will be more available next Monday after I get back from Nashville

**Comment by ultimike** [comment]
I've received the coupon codes for Drupalize.me and have put them in our Google Drive.

**Comment by AmyJuneH** [comment]
@AmyJuneH ping kanopi about assets

**Comment by AmyJuneH** [comment]
Camp concluded. D.O attributions give. Closing issues.
