### ISSUE TITLE
Room monitors - call for volunteers

### ISSUE THREAD

**Issue by AmyJuneH** [mherchel/fldc-issues#175]
Is this something we're interested in doing.. 
Monitors would intro speakers, talk about upcoming events (lunch, parties, etc), CoC reminders, "Push the damn button" reminders...

**Comment by lscook** [comment]
Av wranglers do a lot of this already. If there is anything specific you would like for them to mention we can do that. We usually try and get in and out of the room before the session starts so I'm not sure if all attendees would hear it. AV wranglers introduce themselves to the speaker and make sure they are comfortable with the set up and all equipment is working as it should. If we have enough volunteers, there is usually one person per session room and the room is monitored all day.

**Comment by AmyJuneH** [comment]
ok - thanks for the insights

**Comment by lscook** [comment]
Sure thing. A call for volunteers for AV wranglers is still open. It's a great way to network and meet some really smart people.

**Comment by AmyJuneH** [comment]
Camp concluded. D.O attributions give. Closing issues.
