### ISSUE TITLE
Blank email received on account creation

### ISSUE THREAD

**Issue by mherchel** [mherchel/fldc-issues#18]
May be related to #17 

Received this email (no subject) when I created an account

![image](https://cloud.githubusercontent.com/assets/1605905/12218619/6150c750-b6f2-11e5-882c-7b5ca0376dc5.png)

**Comment by iribarne** [comment]
This is related to #17. After changing the account creation permissions to  "Visitors, but with administrator approval is required." as described in #17, the email received has a subject and body as seen below in screenchot.

![email_received_after_account_creation](https://cloud.githubusercontent.com/assets/617832/12337749/cf6184e2-bad9-11e5-883d-a139f65fdbbf.png)

**Comment by ultimike** [comment]
Hector, 

With the permission fix on #17 can this issue be closed as well?

thanks,  
-mike

**Comment by iribarne** [comment]
Mike,

Yes, the fix for #17 also fixes this ticket.

-Hector

**Comment by mherchel** [comment]
@iribarne Closing, but feel free to close it out, if it's fixed :)
