### ISSUE TITLE
Hover link on front page diver says 2015

### ISSUE THREAD

**Issue by JCL324** [mherchel/fldc-issues#23]

**Comment by ultimike** [comment]
I'm pretty sure this is a theming thing, not a configuration issue. I don't have a checkout of the code, so I can't confirm.

Should be super-easy for any one who has a checkout of the code to do.

-mike

**Comment by JCL324** [comment]
Updated sites/all/themes/fldc14/layouts/zones/zones-layout.tpl.php and pushed to staging branch.
