### ISSUE TITLE
Update featured speakers to only have 3

### ISSUE THREAD

**Issue by mherchel** [mherchel/fldc-issues#25]
Right now the layout has 4. Need to update it and the theming

**Comment by mherchel** [comment]
@JCL324 I updated the css on master. Should I just deploy the code over to staging on Acquia?

**Comment by JCL324** [comment]
all current code is on staging. not sure what's in master now.  I would merge your changes on master into staging and when we're ready to launch, we can do a final merge back to master and deploy to prod. Make sense?

**Comment by mherchel** [comment]
Cool. I cherrypicked the two commits and pushed them to staging. Closing!
