### ISSUE TITLE
Update Mailchimp info

### ISSUE THREAD

**Issue by mherchel** [mherchel/fldc-issues#26]
![image](https://cloud.githubusercontent.com/assets/1605905/12431117/905523e4-bec1-11e5-821c-9f5f35a0f57a.png)

**Comment by JCL324** [comment]
Taking

**Comment by JCL324** [comment]
I found only one reference to 2015 and removed it.  Everything I can find now says Florida Drupal Camp.  Could not find anything 2014.

**Comment by JCL324** [comment]
Mike, if you want to take a look feel free. Otherwise close.

**Comment by mherchel** [comment]
Closing :)
