### ISSUE TITLE
http://www.fldrupalcamp.org redirect not working

### ISSUE THREAD

**Issue by mherchel** [mherchel/fldc-issues#30]
http://www.fldrupalcamp.org/ is not working

**Comment by mherchel** [comment]
Domain still looks good. The IP address doesn't resolve to the same IP as fldrupal.camp

Name servers are all the same (set to Linode). This appears to be a DNS issue.

**Comment by JCL324** [comment]
Nope, it's my ailing Linode in Atlanta.  Ever since Dec. with all their DDOS attacks I keep having to restart Apache occasionally. The IP address is different since the Linode controls the DNS for both domains, but only the live site points to Acquia IPs.
