### ISSUE TITLE
Content - Update Jesus' profile

### ISSUE THREAD

**Issue by mherchel** [mherchel/fldc-issues#8]
It says Blink, where it should be FFW.. verify other stuff too!

http://fldrupalcampstg.prod.acquia-sites.com/users/jmolivas

**Comment by ThatGuyCND** [comment]
we should get Jesus to do this by sending him creds to the user - he'll also be able to add/update his session.

**Comment by ultimike** [comment]
I just sent Jesus an email with his credentials to update.

thanks,  
-mike

**Comment by ultimike** [comment]
It appears that Jesus took care of this on the http://fldrupalcampstg.prod.acquia-sites.com site. Closing.

-mike
